// constants/LanguageContext.tsx
import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';

type Lang = 'de' | 'en';

const translations = {
  de: {
    // General
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    close: 'Schließen',
    add: 'Hinzufügen',
    edit: 'Bearbeiten',
    done: 'Fertig',
    back: 'Zurück',
    loading: 'Laden...',
    error: 'Fehler',
    today: 'Heute',
    yesterday: 'Gestern',
    noData: 'Keine Daten',

    // Home
    home_greeting_night: 'Gute Nacht',
    home_greeting_morning: 'Guten Morgen',
    home_greeting_day: 'Guten Tag',
    home_greeting_evening: 'Guten Abend',
    home_welcome: 'Willkommen zurück',
    home_performance: 'Performance Score',
    home_optimal: 'Optimal',
    home_good: 'Gut',
    home_moderate: 'Moderat',
    home_low: 'Niedrig',
    home_no_entry: 'Kein Eintrag',
    home_sleep_last: 'Schlaf letzte Nacht',
    home_sleep_details: 'Schlaf Details',
    home_fall_asleep: 'Schlafen',
    home_wake_up: 'Aufwachen',
    home_energy: 'Energie & Body Battery',
    home_energy_high: '⚡ Hoch — bereit für intensives Training',
    home_energy_medium: '🔶 Moderat — leichte bis mittlere Belastung',
    home_energy_low: '🔋 Niedrig — Erholung empfohlen',
    home_energy_none: 'Noch kein Eintrag heute',
    home_energy_log: 'Energie eintragen',
    home_nutrition: 'Ernährung heute',
    home_nutrition_goal: 'Ziel',
    home_nutrition_reached: 'erreicht',
    home_nutrition_log: 'Mahlzeit eintragen',
    home_readiness: 'Trainingsbereitschaft',
    home_muscles_ready: 'Muskelgruppen erholt',
    home_start_training: 'Training starten',
    home_recovery: 'Recovery',
    home_habits: 'Habits heute',
    home_journal: 'Tagesnotiz schreiben',
    home_journal_title: 'Tagesnotiz',
    home_journal_placeholder: 'Wie war dein Tag?',
    home_journal_subtitle: 'Wie war dein Tag? Stimmung, Training, Gedanken.',
    home_todo: 'Heute erledigen',
    home_todo_sleep: 'Schlaf erfassen',
    home_todo_checkin: 'Daily Check-in',
    home_todo_battery: 'Body Battery',
    home_todo_journal: 'Tagesnotiz',
    home_streak: 'Tage',

    // Side Menu
    menu_appearance: 'Erscheinungsbild',
    menu_profile: 'Mein Profil',
    menu_athlete_profile: 'Athleten-Profil',
    menu_achievements: 'Abzeichen',
    menu_history: 'Verlauf',
    menu_friends: 'Freunde',
    menu_photos: 'Fortschrittsfotos',
    menu_language: 'Sprache',

    // Training
    training_title: 'Training',
    training_start: 'Training starten',
    training_finish: 'Training beenden',
    training_duration: 'Dauer',
    training_exercises: 'Übungen',
    training_sets: 'Sätze',
    training_reps: 'Wiederholungen',
    training_weight: 'Gewicht',
    training_rest: 'Pause',
    training_pr: 'Persönlicher Rekord',
    training_score: 'Workout Score',
    training_calories: 'Kalorien verbrannt',
    training_add_exercise: 'Übung hinzufügen',
    training_complete: 'Workout abgeschlossen',
    training_streak: 'Streak',

    // Training Screen Extended
    training_swipe_start: 'schieben zum starten',
    training_search_placeholder: 'Übung suchen...',
    training_no_exercise_found: 'Keine Übung gefunden',
    training_exercises_abbr: 'Üb.',
    training_pr_edit: 'PR bearbeiten',
    training_choose_exercise: 'Übung wählen',
    training_pr_update: 'PR aktualisieren',
    training_pr_save: 'PR speichern',
    training_other_exercise: 'Andere Übung wählen',
    training_enter_weight_alert: 'Bitte Gewicht eingeben',
    training_delete_title: 'Training löschen',
    training_delete_confirm: 'Wirklich löschen?',
    training_delete_item: 'löschen?',
    training_units: 'Einheiten',
    training_avg_duration: 'Ø Dauer',
    training_avg_score: 'Ø Score',
    training_no_sessions: 'Noch keine Einheiten',
    training_run_session: 'Lauftraining',
    training_routine_new: 'Neue Routine',
    training_routine_unnamed: 'Unbenannt',
    training_routine_name_required: 'Bitte Namen eingeben',
    training_routine_exercise_required: 'Bitte mindestens eine Übung hinzufügen',
    training_create_yourself: 'Selbst zusammenstellen',
    training_no_routines: 'Noch keine Routinen',
    training_strength: 'Krafttraining',
    training_routines: 'Routinen',
    training_my_routines: 'Meine Routinen',
    training_discover: 'Entdecken',
    training_routine_label: 'Routine',
    training_active: 'Aktiv',
    training_running_label: 'Training läuft',
    training_rest_active: 'Pause läuft',
    training_rest_start: 'Pause starten',
    training_last_time: 'Letztes Mal',
    training_reps_short: 'Wdh.',
    training_rec_tap: 'Tippen zum Übernehmen',
    training_finish_btn: 'Training abschliessen',
    training_run_active: 'Lauf aktiv',
    training_run_time: 'Laufzeit',
    training_run_distance: 'Distanz (km)',
    training_heartrate: 'Herzfreq.',
    training_data: 'Daten',
    training_run_end: 'Lauf beenden',
    training_run_complete: 'Lauf abgeschlossen!',
    training_body_front: 'Vorderseite',
    training_body_back: 'Rückseite',
    training_legend_recovered: 'Erholt',
    training_legend_almost: 'Fast',
    training_legend_medium: 'Mittel',
    training_legend_low: 'Niedrig',
    training_legend_caution: 'Schonen',
    training_rest_today: 'Heute schonen',
    training_ready: 'Bereit',
    body_muscle_recovery: 'Muskel Recovery',
    training_strength_dev: 'Kraftentwicklung',
    training_avg_all_mg: 'Ø aller Muskelgruppen',
    training_this_month: 'diesen Monat',
    training_in_6months: 'in 6 Monaten',
    training_this_year: 'dieses Jahr',
    training_in_2years: 'in 2 Jahren',
    training_total: 'gesamt',
    training_no_data: 'Noch nicht genug Daten',
    training_no_pr_data: 'Nicht genug PR-Daten',
    training_detail_view: 'Detailansicht → Muskelgruppen',
    training_progress: 'Fortschritt',
    training_history_by_mg: 'Verlauf nach Muskelgruppe',
    training_show_hide: 'Ein-/Ausblenden',
    training_ranking_improvement: 'Ranking — Verbesserung',
    training_workout_done: 'Training abgeschlossen',
    training_days_streak: 'Tage Streak',
    training_new_pr: 'Neuer PR',
    training_this_week: 'Diese Woche',
    training_continue: 'Weiter →',
    training_volume: 'Volumen',
    training_today_recommended: 'Heute empfohlen',
    training_start_now: 'Jetzt starten',
    training_free: 'Frei',
    training_muscle_recovery_title: 'Muskelregeneration',
    training_status_ready: 'bereit',
    training_status_caution: 'schonen',
    training_status_medium: 'mittel',
    training_view_details: 'Details ansehen',
    training_prs_title: 'Persönliche Rekorde',
    training_prs_saved: 'Rekorde gespeichert',
    training_history_title: 'Trainingsverlauf',
    training_sessions_unit: 'Einheiten',
    training_nutrition_post: 'Ernährung 🍗',
    training_got_it: 'Verstanden ✓',
    training_free_workout: 'Freies Training',
    training_history_label: 'Verlauf',
    training_timing_now_high: 'Sofort (0–30 Min.)',
    training_timing_later_high: '2–3 Stunden später',
    training_timing_now_medium: 'Sofort (0–45 Min.)',
    training_timing_later_medium: '3–4 Stunden später',
    training_timing_now_low: 'Innerhalb 1 Stunde',
    training_timing_later_low: '4–5 Stunden später',

    // Nutrition
    nutrition_title: 'Ernährung',
    nutrition_score: 'Nutrition Score',
    nutrition_history: 'Verlauf',
    nutrition_report: '📊 Report',
    nutrition_goal: 'Basis-Ziel',
    nutrition_burned: 'Verbrannt',
    nutrition_left: 'Übrig',
    nutrition_macros: 'Makros',
    nutrition_micros: 'Mikronährstoffe',
    nutrition_meals: 'Mahlzeiten',
    nutrition_breakfast: 'Frühstück',
    nutrition_lunch: 'Mittagessen',
    nutrition_dinner: 'Abendessen',
    nutrition_snacks: 'Snacks',
    nutrition_add: 'Kalorien eintragen',
    nutrition_barcode: 'Barcode scannen',
    nutrition_ai: 'KI-Foto',
    nutrition_gallery: 'Aus Galerie',
    nutrition_manual: 'Manuell',
    nutrition_goals: 'Tagesziele',
    nutrition_protein: 'Protein',
    nutrition_carbs: 'Kohlenhydrate',
    nutrition_fat: 'Fett',
    nutrition_kcal: 'Kalorien',
    nutrition_details: 'Details',
    nutrition_product: 'Verpacktes Produkt',
    nutrition_self: 'Selbst eintragen',
    nutrition_photo: 'Mahlzeit fotografieren',
    nutrition_from_gallery: 'Foto aus Bibliothek',
    nutrition_add_entry: 'Eintrag hinzufügen',
    nutrition_nothing: 'Noch nichts',
    nutrition_entries: 'Einträge',
    nutrition_entry: 'Eintrag',
    nutrition_ai_loading: 'KI analysiert Mahlzeit…',
    nutrition_ai_seconds: 'Das dauert ein paar Sekunden',
    nutrition_day_report: 'Tagesreport',
    nutrition_analyzing: 'KI analysiert deinen Tag…',
    nutrition_detected: '🍽 Mahlzeit erkannt',
    nutrition_correct: 'Stimmt das?',
    nutrition_fix: 'Korrigieren',
    nutrition_confirm: 'Hinzufügen ✓',

    // Health
    health_title: 'Health',
    health_hrv: 'HRV',
    health_pulse: 'Ruhepuls',
    health_recovery: 'Recovery',
    health_sleep: 'Schlaf',
    health_body: 'Körper',
    health_history: 'Verlauf',
    health_add: 'Eintragen',

    // Body
    body_title: 'Körper',
    body_recovery: 'Muskel\nRecovery',
    body_front: '▶ Vorderseite',
    body_back: '◀ Rückseite',
    body_legend: 'Recovery',
    body_ready: '✓ Bereit',
    body_warning: '⚠ Noch nicht erholt',
    body_warning_msg: 'heute schonen.',
    body_all: 'Alle Muskelgruppen',
    body_never: 'Nie trainiert',
    body_recovered: 'Erholt ✓',

    // Friends
    friends_title: 'Freunde',
    friends_code: 'Mein Friend-Code',
    friends_stats: 'Deine Stats',
    friends_ranking: 'Rangliste · Streak',
    friends_add: 'Freund hinzufügen',
    friends_share: 'Teilen',
    friends_remove: 'Entfernen',
    friends_empty: 'Noch keine Freunde',
    friends_refresh: 'Aktualisieren',

    // Progress Photos
    photos_title: 'Fortschrittsfotos',
    photos_current: 'Aktuell',
    photos_compare: 'Vergleich',
    photos_before: 'Vorher',
    photos_after: 'Jetzt',
    photos_add: 'Foto hinzufügen',
    photos_empty: 'Noch keine Fotos',
    photos_front: 'Vorne',
    photos_side: 'Seite',
    photos_back: 'Rücken',

    // Mood
    mood_bad: 'Schlecht',
    mood_ok: 'Mäßig',
    mood_okay: 'Okay',
    mood_good: 'Gut',
    mood_great: 'Super',

    // Scores
    score_best: 'Bester Tag',
    score_worst: 'Schwächster',
    score_avg: 'Durchschnitt',

    // Onboarding
    onboarding_welcome_title: 'Willkommen bei\nStride',
    onboarding_welcome_subtitle: 'Dein persönlicher Trainings-, Gesundheits- und Ernährungs-Coach.',
    onboarding_choose_language: 'Sprache wählen',
    onboarding_get_started: "Los geht's →",
    onboarding_features_title: 'Alles an\neinem Ort',
    onboarding_features_subtitle: 'Stride begleitet dich in drei Bereichen.',
    onboarding_feature_training_title: 'Training',
    onboarding_feature_training_desc: 'Workouts tracken, Routinen erstellen, persönliche Rekorde und Muskel-Recovery im Blick behalten.',
    onboarding_feature_health_title: 'Health',
    onboarding_feature_health_desc: 'HRV, Ruhepuls, Schlaf, Body Battery und Trainingsbereitschaft — automatisch aus Apple Health.',
    onboarding_feature_nutrition_title: 'Ernährung',
    onboarding_feature_nutrition_desc: 'Kalorien und Makros erfassen, Mahlzeiten per Foto erkennen lassen und Ziele verfolgen.',
    onboarding_health_title: 'Apple Health\nverbinden',
    onboarding_health_subtitle: 'Stride liest Schlaf, HRV, Ruhepuls und Aktivität aus Apple Health, um deine Erholung und Trainingsbereitschaft zu berechnen. Deine Daten bleiben auf deinem Gerät.',
    onboarding_health_connect: 'Apple Health verbinden',
    onboarding_health_connected: '✓ Verbunden',
    onboarding_health_skip: 'Später verbinden',
    onboarding_health_unavailable: 'Apple Health ist auf diesem Gerät nicht verfügbar.',
    onboarding_profile_title: 'Dein\nProfil',
    onboarding_profile_subtitle: 'Damit dir Stride passende Empfehlungen geben kann.',
    onboarding_name_label: 'Name',
    onboarding_name_placeholder: 'Dein Name',
    onboarding_age_label: 'Alter',
    onboarding_height_label: 'Größe (cm)',
    onboarding_weight_label: 'Gewicht (kg)',
    onboarding_goal_label: 'Was ist dein Ziel?',
    onboarding_finish: 'Loslegen 🚀',
    onboarding_back: '← Zurück',
    onboarding_next: 'Weiter →',
    onboarding_name_required: 'Bitte gib deinen Namen ein',
    onboarding_goal_masse: 'Masse aufbauen',
    onboarding_goal_kraft: 'Stärker werden',
    onboarding_goal_wettkampf: 'Wettkampf',
    onboarding_goal_abnehmen: 'Gewicht verlieren',
    onboarding_goal_gesundheit: 'Gesund bleiben',
    onboarding_goal_performance: 'Performance',

    // Notifications
    notif_settings_title: 'Benachrichtigungen',
    notif_settings_subtitle: 'Erinnerungen anpassen',
    notif_health_reminder: 'Gesundheitsdaten erfassen',
    notif_health_reminder_desc: 'Tägliche Erinnerung, Schlaf, HRV & Stimmung einzutragen.',
    notif_training_reminder: 'Trainingserinnerung',
    notif_training_reminder_desc: 'Wöchentliche Erinnerung an deinen Trainingstag.',
    notif_nutrition_reminder: 'Ernährungshinweis nach Training',
    notif_nutrition_reminder_desc: 'Hinweis 30 Minuten nach Trainingsende, um Mahlzeit/Protein einzutragen.',
    notif_time: 'Uhrzeit',
    notif_weekday: 'Wochentag',
    notif_permission_denied: 'Benachrichtigungen sind deaktiviert. Bitte in den Systemeinstellungen aktivieren.',
    notif_health_title: 'Zeit für deinen Check-in',
    notif_health_body: 'Trage Schlaf, HRV und Stimmung ein, um deine Trainingsbereitschaft aktuell zu halten.',
    notif_training_title: 'Trainingszeit 💪',
    notif_training_body: 'Heute steht dein Training an — bereit?',
    notif_nutrition_title: 'Ernährung nicht vergessen 🍗',
    notif_nutrition_body: 'Zeit für eine proteinreiche Mahlzeit, um die Erholung zu unterstützen.',
    weekday_mon: 'Montag', weekday_tue: 'Dienstag', weekday_wed: 'Mittwoch', weekday_thu: 'Donnerstag',
    weekday_fri: 'Freitag', weekday_sat: 'Samstag', weekday_sun: 'Sonntag',

    // Widgets
    widget_settings_title: 'Widgets',
    widget_settings_subtitle: 'Home- & Sperrbildschirm anpassen',
    widget_size_small: 'Klein',
    widget_size_medium: 'Mittel',
    widget_size_large: 'Groß',
    widget_size_lock: 'Sperrbildschirm',
    widget_choose_content: 'Inhalt wählen',
    widget_slot: 'Feld',
    widget_metric_battery: 'Body Battery',
    widget_metric_readiness: 'Trainingsbereitschaft',
    widget_metric_steps: 'Schritte heute',
    widget_metric_calories: 'Kalorien heute',
    widget_metric_resting_hr: 'Ruhepuls',
    widget_metric_hrv: 'HRV',
    widget_metric_streak: 'Streak',
    widget_metric_next_workout: 'Nächstes Training',
    widget_metric_sleep: 'Schlafqualität',
    widget_metric_stress: 'Stress Score',
    widget_metric_muscle_recovery: 'Muskel Recovery',
    widget_metric_weight: 'Gewicht',
    widget_metric_nutrition: 'Nutrition Score',
    widget_metric_vo2max: 'VO2max',
    widget_metric_last_workout: 'Letztes Workout',
    widget_save: 'Speichern',
    widget_saved: 'Widget-Einstellungen gespeichert',
    widget_preview: 'Vorschau',
    widget_info: 'Lege fest, was auf jeder Widget-Größe angezeigt wird. Füge das Widget über den Home- oder Sperrbildschirm hinzu (gedrückt halten → Widget hinzufügen → Stride).',
  },

  en: {
    // General
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    close: 'Close',
    add: 'Add',
    edit: 'Edit',
    done: 'Done',
    back: 'Back',
    loading: 'Loading...',
    error: 'Error',
    today: 'Today',
    yesterday: 'Yesterday',
    noData: 'No data',

    // Home
    home_greeting_night: 'Good Night',
    home_greeting_morning: 'Good Morning',
    home_greeting_day: 'Good Day',
    home_greeting_evening: 'Good Evening',
    home_welcome: 'Welcome back',
    home_performance: 'Performance Score',
    home_optimal: 'Optimal',
    home_good: 'Good',
    home_moderate: 'Moderate',
    home_low: 'Low',
    home_no_entry: 'No Entry',
    home_sleep_last: 'Last Night\'s Sleep',
    home_sleep_details: 'Sleep Details',
    home_fall_asleep: 'Bedtime',
    home_wake_up: 'Wake Up',
    home_energy: 'Energy & Body Battery',
    home_energy_high: '⚡ High — ready for intense training',
    home_energy_medium: '🔶 Moderate — light to medium load',
    home_energy_low: '🔋 Low — recovery recommended',
    home_energy_none: 'No entry today yet',
    home_energy_log: 'Log energy',
    home_nutrition: 'Today\'s Nutrition',
    home_nutrition_goal: 'Goal',
    home_nutrition_reached: 'reached',
    home_nutrition_log: 'Log meal',
    home_readiness: 'Training Readiness',
    home_muscles_ready: 'muscle groups recovered',
    home_start_training: 'Start Training',
    home_recovery: 'Recovery',
    home_habits: 'Today\'s Habits',
    home_journal: 'Write daily note',
    home_journal_title: 'Daily Note',
    home_journal_placeholder: 'How was your day?',
    home_journal_subtitle: 'How was your day? Mood, training, thoughts.',
    home_todo: 'Today\'s Tasks',
    home_todo_sleep: 'Log sleep',
    home_todo_checkin: 'Daily Check-in',
    home_todo_battery: 'Body Battery',
    home_todo_journal: 'Daily Note',
    home_streak: 'days',

    // Side Menu
    menu_appearance: 'Appearance',
    menu_profile: 'My Profile',
    menu_athlete_profile: 'Athlete Profile',
    menu_achievements: 'Achievements',
    menu_history: 'History',
    menu_friends: 'Friends',
    menu_photos: 'Progress Photos',
    menu_language: 'Language',

    // Training
    training_title: 'Training',
    training_start: 'Start Training',
    training_finish: 'Finish Workout',
    training_duration: 'Duration',
    training_exercises: 'Exercises',
    training_sets: 'Sets',
    training_reps: 'Reps',
    training_weight: 'Weight',
    training_rest: 'Rest',
    training_pr: 'Personal Record',
    training_score: 'Workout Score',
    training_calories: 'Calories burned',
    training_add_exercise: 'Add Exercise',
    training_complete: 'Workout Complete',
    training_streak: 'Streak',

    // Training Screen Extended
    training_swipe_start: 'swipe to start',
    training_search_placeholder: 'Search exercise...',
    training_no_exercise_found: 'No exercise found',
    training_exercises_abbr: 'ex.',
    training_pr_edit: 'Edit PR',
    training_choose_exercise: 'Choose exercise',
    training_pr_update: 'Update PR',
    training_pr_save: 'Save PR',
    training_other_exercise: 'Choose different exercise',
    training_enter_weight_alert: 'Please enter weight',
    training_delete_title: 'Delete workout',
    training_delete_confirm: 'Really delete?',
    training_delete_item: 'delete?',
    training_units: 'Sessions',
    training_avg_duration: 'Avg Duration',
    training_avg_score: 'Avg Score',
    training_no_sessions: 'No sessions yet',
    training_run_session: 'Running',
    training_routine_new: 'New Routine',
    training_routine_unnamed: 'Unnamed',
    training_routine_name_required: 'Please enter a name',
    training_routine_exercise_required: 'Please add at least one exercise',
    training_create_yourself: 'Create your own',
    training_no_routines: 'No routines yet',
    training_strength: 'Strength Training',
    training_routines: 'Routines',
    training_my_routines: 'My Routines',
    training_discover: 'Discover',
    training_routine_label: 'Routine',
    training_active: 'Active',
    training_running_label: 'Workout running',
    training_rest_active: 'Rest active',
    training_rest_start: 'Start rest',
    training_last_time: 'Last time',
    training_reps_short: 'Reps',
    training_rec_tap: 'Tap to apply',
    training_finish_btn: 'Finish workout',
    training_run_active: 'Run active',
    training_run_time: 'Run time',
    training_run_distance: 'Distance (km)',
    training_heartrate: 'Heart rate',
    training_data: 'Data',
    training_run_end: 'End run',
    training_run_complete: 'Run complete!',
    training_body_front: 'Front',
    training_body_back: 'Back',
    training_legend_recovered: 'Recovered',
    training_legend_almost: 'Almost',
    training_legend_medium: 'Medium',
    training_legend_low: 'Low',
    training_legend_caution: 'Rest',
    training_rest_today: 'Rest today',
    training_ready: 'Ready',
    body_muscle_recovery: 'Muscle Recovery',
    training_strength_dev: 'Strength Development',
    training_avg_all_mg: 'Avg of all muscle groups',
    training_this_month: 'this month',
    training_in_6months: 'in 6 months',
    training_this_year: 'this year',
    training_in_2years: 'in 2 years',
    training_total: 'total',
    training_no_data: 'Not enough data yet',
    training_no_pr_data: 'Not enough PR data',
    training_detail_view: 'Detail view → Muscle groups',
    training_progress: 'Progress',
    training_history_by_mg: 'History by muscle group',
    training_show_hide: 'Show/Hide',
    training_ranking_improvement: 'Ranking — Improvement',
    training_workout_done: 'Workout complete',
    training_days_streak: 'Day Streak',
    training_new_pr: 'New PR',
    training_this_week: 'This Week',
    training_continue: 'Continue →',
    training_volume: 'Volume',
    training_today_recommended: "Today's recommendation",
    training_start_now: 'Start now',
    training_free: 'Free',
    training_muscle_recovery_title: 'Muscle recovery',
    training_status_ready: 'ready',
    training_status_caution: 'rest',
    training_status_medium: 'medium',
    training_view_details: 'View details',
    training_prs_title: 'Personal Records',
    training_prs_saved: 'records saved',
    training_history_title: 'Training history',
    training_sessions_unit: 'sessions',
    training_nutrition_post: 'Nutrition 🍗',
    training_got_it: 'Got it ✓',
    training_free_workout: 'Free Workout',
    training_history_label: 'History',
    training_timing_now_high: 'Right away (0–30 min)',
    training_timing_later_high: '2–3 hours later',
    training_timing_now_medium: 'Right away (0–45 min)',
    training_timing_later_medium: '3–4 hours later',
    training_timing_now_low: 'Within 1 hour',
    training_timing_later_low: '4–5 hours later',

    // Nutrition
    nutrition_title: 'Nutrition',
    nutrition_score: 'Nutrition Score',
    nutrition_history: 'History',
    nutrition_report: '📊 Report',
    nutrition_goal: 'Base Goal',
    nutrition_burned: 'Burned',
    nutrition_left: 'Remaining',
    nutrition_macros: 'Macros',
    nutrition_micros: 'Micronutrients',
    nutrition_meals: 'Meals',
    nutrition_breakfast: 'Breakfast',
    nutrition_lunch: 'Lunch',
    nutrition_dinner: 'Dinner',
    nutrition_snacks: 'Snacks',
    nutrition_add: 'Log calories',
    nutrition_barcode: 'Scan barcode',
    nutrition_ai: 'AI Photo',
    nutrition_gallery: 'From Gallery',
    nutrition_manual: 'Manual',
    nutrition_goals: 'Daily Goals',
    nutrition_protein: 'Protein',
    nutrition_carbs: 'Carbohydrates',
    nutrition_fat: 'Fat',
    nutrition_kcal: 'Calories',
    nutrition_details: 'Details',
    nutrition_product: 'Packaged product',
    nutrition_self: 'Enter manually',
    nutrition_photo: 'Photograph meal',
    nutrition_from_gallery: 'Photo from library',
    nutrition_add_entry: 'Add entry',
    nutrition_nothing: 'Nothing yet',
    nutrition_entries: 'entries',
    nutrition_entry: 'entry',
    nutrition_ai_loading: 'AI analyzing meal…',
    nutrition_ai_seconds: 'This takes a few seconds',
    nutrition_day_report: 'Day Report',
    nutrition_analyzing: 'AI analyzing your day…',
    nutrition_detected: '🍽 Meal detected',
    nutrition_correct: 'Is this correct?',
    nutrition_fix: 'Correct',
    nutrition_confirm: 'Add ✓',

    // Health
    health_title: 'Health',
    health_hrv: 'HRV',
    health_pulse: 'Resting Pulse',
    health_recovery: 'Recovery',
    health_sleep: 'Sleep',
    health_body: 'Body',
    health_history: 'History',
    health_add: 'Log',

    // Body
    body_title: 'Body',
    body_recovery: 'Muscle\nRecovery',
    body_front: '▶ Front',
    body_back: '◀ Back',
    body_legend: 'Recovery',
    body_ready: '✓ Ready',
    body_warning: '⚠ Not recovered yet',
    body_warning_msg: 'rest today.',
    body_all: 'All Muscle Groups',
    body_never: 'Never trained',
    body_recovered: 'Recovered ✓',

    // Friends
    friends_title: 'Friends',
    friends_code: 'My Friend Code',
    friends_stats: 'Your Stats',
    friends_ranking: 'Leaderboard · Streak',
    friends_add: 'Add Friend',
    friends_share: 'Share',
    friends_remove: 'Remove',
    friends_empty: 'No friends yet',
    friends_refresh: 'Refresh',

    // Progress Photos
    photos_title: 'Progress Photos',
    photos_current: 'Current',
    photos_compare: 'Compare',
    photos_before: 'Before',
    photos_after: 'Now',
    photos_add: 'Add photo',
    photos_empty: 'No photos yet',
    photos_front: 'Front',
    photos_side: 'Side',
    photos_back: 'Back',

    // Mood
    mood_bad: 'Bad',
    mood_ok: 'Poor',
    mood_okay: 'Okay',
    mood_good: 'Good',
    mood_great: 'Great',

    // Scores
    score_best: 'Best Day',
    score_worst: 'Weakest',
    score_avg: 'Average',

    // Onboarding
    onboarding_welcome_title: 'Welcome to\nStride',
    onboarding_welcome_subtitle: 'Your personal training, health and nutrition coach.',
    onboarding_choose_language: 'Choose language',
    onboarding_get_started: "Get started →",
    onboarding_features_title: 'Everything in\none place',
    onboarding_features_subtitle: 'Stride supports you in three areas.',
    onboarding_feature_training_title: 'Training',
    onboarding_feature_training_desc: 'Track workouts, build routines, keep an eye on personal records and muscle recovery.',
    onboarding_feature_health_title: 'Health',
    onboarding_feature_health_desc: 'HRV, resting heart rate, sleep, Body Battery and training readiness — automatically from Apple Health.',
    onboarding_feature_nutrition_title: 'Nutrition',
    onboarding_feature_nutrition_desc: 'Log calories and macros, recognize meals by photo, and track your goals.',
    onboarding_health_title: 'Connect\nApple Health',
    onboarding_health_subtitle: 'Stride reads sleep, HRV, resting heart rate and activity from Apple Health to calculate your recovery and training readiness. Your data stays on your device.',
    onboarding_health_connect: 'Connect Apple Health',
    onboarding_health_connected: '✓ Connected',
    onboarding_health_skip: 'Connect later',
    onboarding_health_unavailable: 'Apple Health is not available on this device.',
    onboarding_profile_title: 'Your\nProfile',
    onboarding_profile_subtitle: 'So Stride can give you tailored recommendations.',
    onboarding_name_label: 'Name',
    onboarding_name_placeholder: 'Your name',
    onboarding_age_label: 'Age',
    onboarding_height_label: 'Height (cm)',
    onboarding_weight_label: 'Weight (kg)',
    onboarding_goal_label: 'What is your goal?',
    onboarding_finish: "Let's go 🚀",
    onboarding_back: '← Back',
    onboarding_next: 'Next →',
    onboarding_name_required: 'Please enter your name',
    onboarding_goal_masse: 'Build muscle',
    onboarding_goal_kraft: 'Get stronger',
    onboarding_goal_wettkampf: 'Competition',
    onboarding_goal_abnehmen: 'Lose weight',
    onboarding_goal_gesundheit: 'Stay healthy',
    onboarding_goal_performance: 'Performance',

    // Notifications
    notif_settings_title: 'Notifications',
    notif_settings_subtitle: 'Customize reminders',
    notif_health_reminder: 'Log health data',
    notif_health_reminder_desc: 'Daily reminder to log sleep, HRV & mood.',
    notif_training_reminder: 'Training reminder',
    notif_training_reminder_desc: 'Weekly reminder for your training day.',
    notif_nutrition_reminder: 'Post-workout nutrition tip',
    notif_nutrition_reminder_desc: 'Reminder 30 minutes after your workout ends to log a meal/protein.',
    notif_time: 'Time',
    notif_weekday: 'Weekday',
    notif_permission_denied: 'Notifications are disabled. Please enable them in system settings.',
    notif_health_title: 'Time for your check-in',
    notif_health_body: 'Log sleep, HRV and mood to keep your training readiness up to date.',
    notif_training_title: 'Training time 💪',
    notif_training_body: 'Your training session is coming up — ready?',
    notif_nutrition_title: "Don't forget nutrition 🍗",
    notif_nutrition_body: 'Time for a protein-rich meal to support recovery.',
    weekday_mon: 'Monday', weekday_tue: 'Tuesday', weekday_wed: 'Wednesday', weekday_thu: 'Thursday',
    weekday_fri: 'Friday', weekday_sat: 'Saturday', weekday_sun: 'Sunday',

    // Widgets
    widget_settings_title: 'Widgets',
    widget_settings_subtitle: 'Customize home & lock screen',
    widget_size_small: 'Small',
    widget_size_medium: 'Medium',
    widget_size_large: 'Large',
    widget_size_lock: 'Lock Screen',
    widget_choose_content: 'Choose content',
    widget_slot: 'Slot',
    widget_metric_battery: 'Body Battery',
    widget_metric_readiness: 'Training Readiness',
    widget_metric_steps: 'Steps Today',
    widget_metric_calories: 'Calories Today',
    widget_metric_resting_hr: 'Resting HR',
    widget_metric_hrv: 'HRV',
    widget_metric_streak: 'Streak',
    widget_metric_next_workout: 'Next Workout',
    widget_metric_sleep: 'Sleep Quality',
    widget_metric_stress: 'Stress Score',
    widget_metric_muscle_recovery: 'Muscle Recovery',
    widget_metric_weight: 'Weight',
    widget_metric_nutrition: 'Nutrition Score',
    widget_metric_vo2max: 'VO2max',
    widget_metric_last_workout: 'Last Workout',
    widget_save: 'Save',
    widget_saved: 'Widget settings saved',
    widget_preview: 'Preview',
    widget_info: 'Choose what appears on each widget size. Add the widget from the home or lock screen (long press → Add Widget → Stride).',
  },
};

type TranslationKey = keyof typeof translations.de;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'de',
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('de');

  useEffect(() => {
    AsyncStorage.getItem('appLanguage').then(l => {
      if (l === 'de' || l === 'en') setLangState(l);
    });
  }, []);

  const setLang = useCallback(async (l: Lang) => {
    setLangState(l);
    await AsyncStorage.setItem('appLanguage', l);
  }, []);

  const t = useCallback((key: TranslationKey): string => {
    return translations[lang][key] ?? translations.de[key] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export type { Lang, TranslationKey };
